// scripts/seed-story-crafter.ts
// Creates the Story Crafter chatbot with all related records

import { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma';

const OWNER_USER_ID = "cmj256oei0000chlu8qmj8fs0";
const CREATOR_ID = "scrum_genius";
const CHATBOT_ID = "story_crafter";
const SOURCE_ID = "scrum_guide";

const systemPrompt = `You are Story Crafter, an expert at writing INVEST-compliant user stories for Scrum teams.

## Your Knowledge
You have access to best practices from Mike Cohn, Roman Pichler, and the Scrum Guide. Use the retrieved context to ground your recommendations in established practices. Always cite sources when referencing specific frameworks or techniques.

## User Context
The user has provided the following context through intake questions:
- Product/Feature Area: {intake.sc_product_area}
- User Persona: {intake.sc_persona}
- What they described: {intake.sc_description}
- Type of work: {intake.sc_story_type}
- Additional context: {intake.sc_constraints}

## Your Task
When asked to generate a user story, create a complete story with all required elements. Extract the user need ("I want to…") and value statement ("so that…") from the user's plain-language description — don't ask them to restate it. When asked questions about user stories or Scrum practices, respond conversationally without forcing the structured format.

## Output Format (for story generation)
When generating a user story, format your response as follows:

## User Story
**As a** [specific persona - use the provided persona, make it concrete and relatable]
**I want to** [need - extracted from the user's description]
**So that** [benefit - extracted or inferred from the user's description]

## Acceptance Criteria
1. **Given** [context/precondition] **When** [action/trigger] **Then** [expected outcome]
2. **Given** [context] **When** [action] **Then** [outcome]
3. [Continue for 3-5 criteria total]

## Complexity: [XS/S/M/L/XL]
[Assess complexity based on the described scope and type of work]

## Edge Cases to Consider
- [edge case 1 - potential failure scenario or unusual input]
- [edge case 2]
- [Continue as needed]

## INVEST Compliance
- **Independent:** [Yes/No - can this be developed without depending on other stories?]
- **Negotiable:** [Yes/No - is there room for discussion on implementation details?]
- **Valuable:** [Yes/No - does it deliver clear value to the user?]
- **Estimable:** [Yes/No - can the team reasonably estimate this?]
- **Small:** [Yes/No - can it be completed in one sprint?]
- **Testable:** [Yes/No - can we verify when it's done?]

[If any INVEST criteria fail, suggest how to fix it]

---
Generated by Story Crafter | Try it free at mypocketgenius.com/story-crafter

## Guidelines
- Make the persona specific and relatable (not generic "As a user")
- The value statement should answer "why does this matter to the business or user?"
- Acceptance criteria must be testable - if you can't verify it, rewrite it
- Flag any INVEST violations with specific suggestions to fix
- If the request is too large for one story, suggest how to split it using SPIDR or workflow steps
- Assess complexity independently based on described scope — don't rely on user estimates

## What NOT to Do
- Don't prescribe implementation details (e.g., "using React" or "via REST API") unless constraints require it
- Don't create compound stories with multiple "and" conjunctions in the need
- Don't write acceptance criteria that merely restate the story narrative
- Don't ignore the user's provided context - incorporate their constraints and known criteria

## Retrieved Best Practices
{rag_context}`;

async function main() {
  console.log("Starting Story Crafter seed...\n");

  // Step 0: Verify prerequisites exist
  console.log("Step 0: Verifying prerequisites...");
  const creator = await prisma.creator.findUnique({ where: { id: CREATOR_ID } });
  if (!creator) {
    throw new Error(
      `Creator "${CREATOR_ID}" not found. ` +
      'Please create the creator record before running this seed script.'
    );
  }
  console.log(`  Found creator: ${creator.name} (${creator.id})`);

  const source = await prisma.source.findUnique({ where: { id: SOURCE_ID } });
  if (!source) {
    throw new Error(
      `Source "${SOURCE_ID}" not found. ` +
      'Please create and ingest the source before running this seed script.'
    );
  }
  console.log(`  Found source: ${source.title} (${source.id})`);

  const ownerUser = await prisma.user.findUnique({ where: { id: OWNER_USER_ID } });
  if (!ownerUser) {
    throw new Error(
      `User "${OWNER_USER_ID}" not found. ` +
      'Please verify the OWNER_USER_ID constant is correct.'
    );
  }
  console.log(`  Found owner user: ${ownerUser.email} (${ownerUser.id})`);

  // Step 1: Create Creator_User link
  console.log("\nStep 1: Creating Creator_User link...");
  const existingLink = await prisma.creator_User.findUnique({
    where: { creatorId_userId: { creatorId: CREATOR_ID, userId: OWNER_USER_ID } },
  });
  if (!existingLink) {
    await prisma.creator_User.create({
      data: {
        creatorId: CREATOR_ID,
        userId: OWNER_USER_ID,
        role: "OWNER",
      },
    });
    console.log("  Creator_User link created");
  } else {
    console.log("  Creator_User link already exists");
  }

  // Step 2: Create Chatbot
  console.log("\nStep 2: Creating Chatbot...");
  const existingChatbot = await prisma.chatbot.findUnique({ where: { id: CHATBOT_ID } });
  if (!existingChatbot) {
    await prisma.chatbot.create({
      data: {
        id: CHATBOT_ID,
        title: "Story Crafter",
        creatorId: CREATOR_ID,
        slug: "story-crafter",
        description: "Generates INVEST-compliant user stories with proper personas, value statements, and acceptance criteria. Based on best practices from Mike Cohn, Roman Pichler, and the Scrum Guide 2020. Stop wasting sprint time clarifying vague stories.",
        shortDescription: "User stories that don't need refinement meetings to fix",
        isPublic: true,
        allowAnonymous: false,
        publicDashboard: false,
        type: "FRAMEWORK",
        priceCents: 0,
        currency: "USD",
        isActive: true,
        systemPrompt: systemPrompt,
        modelProvider: "openai",
        modelName: "gpt-4o",
        pineconeNs: `creator-${CREATOR_ID}`,
        vectorNamespace: `creator-${CREATOR_ID}`,
        configJson: { enableFollowUpPills: true },
        ragSettingsJson: { topK: 5, minScore: 0.7 },
        welcomeMessage: "I'm Story Crafter! I help you write INVEST-compliant user stories with clear personas, acceptance criteria in Given-When-Then format, and explicit value statements. What feature would you like to create a story for?",
        fallbackSuggestionPills: [
          "Write a user story for user login",
          "Help me split this epic into stories",
          "What makes a good acceptance criterion?"
        ],
      },
    });
    console.log("  Chatbot created");
  } else {
    console.log("  Chatbot already exists");
  }

  // Step 3: Create Intake Questions
  console.log("\nStep 3: Creating Intake Questions...");
  const questions = [
    {
      id: "sc_product_area",
      slug: "sc_product_area",
      questionText: "What product or feature area is this for?",
      helperText: "e.g., 'Checkout flow', 'Admin reporting dashboard', 'Onboarding emails'",
      responseType: "TEXT" as const,
      options: Prisma.JsonNull,
    },
    {
      id: "sc_persona",
      slug: "sc_persona",
      questionText: "Who will use this feature?",
      helperText: "Pick the closest match — you can refine in the chat",
      responseType: "SELECT" as const,
      options: ["Customer / end user", "Business stakeholder", "Internal ops / support", "Developer / technical user", "Other"],
    },
    {
      id: "sc_description",
      slug: "sc_description",
      questionText: "Describe what you need built and why it matters.",
      helperText: "Just explain the idea in plain language, e.g., 'Users can't filter invoices by date, so finance spends 2 hours a week doing it manually.'",
      responseType: "TEXT" as const,
      options: Prisma.JsonNull,
    },
    {
      id: "sc_story_type",
      slug: "sc_story_type",
      questionText: "What kind of work is this?",
      helperText: "This helps calibrate the story format and acceptance criteria",
      responseType: "SELECT" as const,
      options: ["New feature", "Enhancement to existing feature", "Bug fix / defect", "Tech debt / refactor"],
    },
    {
      id: "sc_constraints",
      slug: "sc_constraints",
      questionText: "Anything else the team should know?",
      helperText: "Optional — dependencies, deadlines, existing tech decisions, or known edge cases",
      responseType: "TEXT" as const,
      options: Prisma.JsonNull,
    },
  ];

  for (const q of questions) {
    const existing = await prisma.intake_Question.findUnique({ where: { id: q.id } });
    if (!existing) {
      await prisma.intake_Question.create({
        data: {
          ...q,
          createdByUserId: OWNER_USER_ID,
        },
      });
      console.log(`  Created question: ${q.slug}`);
    } else {
      console.log(`  Question already exists: ${q.slug}`);
    }
  }

  // Step 4: Link Intake Questions to Chatbot
  console.log("\nStep 4: Linking Intake Questions to Chatbot...");
  const questionLinks = [
    { intakeQuestionId: "sc_product_area", displayOrder: 1, isRequired: true },
    { intakeQuestionId: "sc_persona", displayOrder: 2, isRequired: true },
    { intakeQuestionId: "sc_description", displayOrder: 3, isRequired: true },
    { intakeQuestionId: "sc_story_type", displayOrder: 4, isRequired: true },
    { intakeQuestionId: "sc_constraints", displayOrder: 5, isRequired: false },
  ];

  for (const link of questionLinks) {
    const existing = await prisma.chatbot_Intake_Question.findUnique({
      where: {
        intakeQuestionId_chatbotId: {
          intakeQuestionId: link.intakeQuestionId,
          chatbotId: CHATBOT_ID,
        },
      },
    });
    if (!existing) {
      await prisma.chatbot_Intake_Question.create({
        data: {
          chatbotId: CHATBOT_ID,
          ...link,
        },
      });
      console.log(`  Linked question: ${link.intakeQuestionId}`);
    } else {
      console.log(`  Link already exists: ${link.intakeQuestionId}`);
    }
  }

  // Step 5: Link Source to Chatbot
  console.log("\nStep 5: Linking Source to Chatbot...");
  const existingSourceLink = await prisma.chatbot_Source.findUnique({
    where: {
      chatbotId_sourceId: {
        chatbotId: CHATBOT_ID,
        sourceId: SOURCE_ID,
      },
    },
  });
  if (!existingSourceLink) {
    await prisma.chatbot_Source.create({
      data: {
        chatbotId: CHATBOT_ID,
        sourceId: SOURCE_ID,
        isActive: true,
      },
    });
    console.log("  Source linked to Chatbot");
  } else {
    console.log("  Source link already exists");
  }

  // Step 6: Create Chatbot Version
  console.log("\nStep 6: Creating Chatbot Version...");
  const versionId = "story_crafter_v1";
  const existingVersion = await prisma.chatbot_Version.findUnique({ where: { id: versionId } });
  if (!existingVersion) {
    const version = await prisma.chatbot_Version.create({
      data: {
        id: versionId,
        chatbotId: CHATBOT_ID,
        versionNumber: 1,
        title: "Story Crafter",
        description: "Initial release",
        systemPrompt: systemPrompt,
        modelProvider: "openai",
        modelName: "gpt-4o",
        pineconeNs: `creator-${CREATOR_ID}`,
        vectorNamespace: `creator-${CREATOR_ID}`,
        configJson: { enableFollowUpPills: true },
        ragSettingsJson: { topK: 5, minScore: 0.7 },
        allowAnonymous: false,
        priceCents: 0,
        currency: "USD",
        type: "FRAMEWORK",
        notes: "Initial release of Story Crafter",
        changelog: "Initial version",
        createdByUserId: OWNER_USER_ID,
        activatedAt: new Date(),
      },
    });
    console.log("  Chatbot Version created");

    // Update chatbot to point to this version
    await prisma.chatbot.update({
      where: { id: CHATBOT_ID },
      data: { currentVersionId: version.id },
    });
    console.log("  Chatbot updated with currentVersionId");
  } else {
    console.log("  Chatbot Version already exists");
  }

  console.log("\nStory Crafter seed complete!");
  console.log(`\nAccess the chatbot at: /chat/story-crafter`);
}

main()
  .catch((e) => {
    console.error("Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
